// packages/@freshie/ui.preact/_error.jsx
import { h, Fragment } from 'preact';

export function preload(req, context) {
	console.log('_error.jsx got:', req, context);
	return { status: context.status }
}

const messages = {
	'400': 'Bad Request',
	'404': 'Page Not Found',
	'429': 'Too Many Requests',
	'500': 'Unknown Error',
}

export default function Error(props) {
	const { status=500 } = props;

	return (
		<>
			<h1>Error ({status})</h1>
			<p>{ messages[status] }</p>
		</>
	);
}

// packages/@freshie/ui.svelte/_error.svelte
<script context="module">
	export function preload(req, context) {
		// console.log('_error.svelte got:', req, context);
		return { status: context.status }
	}
</script>

<script>
	export let status = 500;

	const messages = {
		'400': 'Bad Request',
		'404': 'Page Not Found',
		'429': 'Too Many Requests',
		'500': 'Unknown Error',
	}
</script>

<h1>Error ({status})</h1>
<p>{ messages[status] }</p>
