// examples/svelte.typescript/src/routes/blog/[id].svelte
<script context="module" lang="ts">
	import { get } from 'freshie/http';
	import type { Request } from 'freshie';

	export async function preload(req: Request) {
		let res = await get(`https://jsonplaceholder.typicode.com/posts/${req.params.id}`);
		return { article: res.data };
	}
</script>

<script lang="ts">
	export let article: Record<string, string>;
</script>

<svelte:head>
	<title>{article.title}</title>
</svelte:head>

<h1>{article.title}</h1>

<div class="content">
	{@html article.body}
</div>

// examples/preact.esbuild/src/routes/blog/[id].jsx
import { get } from 'freshie/http';
import { h, Fragment } from 'preact';

export async function preload(req) {
	let res = await get(`https://jsonplaceholder.typicode.com/posts/${req.params.id}`);
	return { article: res.data };
}

export default function Article(props) {
	// {/* <svelte:head>
	// 	<title>{article.title}</title>
	// </svelte:head> */}
	return (
		<>
			<h1>{ props.article.title }</h1>
			<div className="content" dangerouslySetInnerHTML={{ __html: props.article.body }} />
		</>
	)
}
