// examples/svelte/src/routes/blog/[id].svelte
<script context="module">
	export async function preload(req) {
		let res = await fetch(`https://jsonplaceholder.typicode.com/posts/${req.params.id}`);
		let article = await res.json();
		return { article };
	}
</script>

<script>
	export let article;
</script>

<svelte:head>
	<title>{article.title}</title>
</svelte:head>

<h1>{article.title}</h1>

<div class="content">
	{@html article.body}
</div>

// examples/preact/src/routes/blog/[id].jsx
import { h, Fragment } from 'preact';

export async function preload(req) {
	let res = await fetch(`https://jsonplaceholder.typicode.com/posts/${req.params.id}`);
	let article = await res.json();
	return { article };
}

export default function Article(props) {
	// {/* <svelte:head>
	// 	<title>{article.title}</title>
	// </svelte:head> */}
	return (
		<>
			<h1>{ props.article.title }</h1>
			<div class="content" dangerouslySetInnerHTML={{ __html: props.article.body }} />
		</>
	)
}
