// examples/vue/src/routes/blog/[id].vue
<template>
	<div>
		<h1>{{ article.title }}</h1>
		<div class="content" v-html="article.body" />
	</div>
</template>

<script>
	export async function preload(req) {
		let res = await fetch(`https://jsonplaceholder.typicode.com/posts/${req.params.id}`);
		let article = await res.json();
		console.log('PRELOADED', article);
		return { article };
	}

	export default {
		props: ['article'],
		data() {
			return {
				article: {}
			};
		}
	}

	// <svelte:head>
	// 	<title>{article.title}</title>
	// </svelte:head>
</script>

// examples/svelte/src/routes/blog/[id].svelte
<script context="module">
	export async function preload(req) {
		let res = await fetch(`https://jsonplaceholder.typicode.com/posts/${req.params.id}`);
		let article = await res.json();
		return { article };
	}
</script>

<script>
	export let article;
</script>

<svelte:head>
	<title>{article.title}</title>
</svelte:head>

<h1>{article.title}</h1>

<div class="content">
	{@html article.body}
</div>
